on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '9.0.x'
      - run: |
          dotnet publish ./src/CSharpSales/CSharpSales.csproj -c Release -o publish
          cd publish
          zip -r deploy.zip .
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: CSharpSales
          environment_name: CSharpSales-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: publish/deploy.zip
