name: Deploy CSharpSales .NET9 AWS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '9.0.x'
          
      - name: Publish
        run: dotnet publish ./src/CSharpSales/CSharpSales.csproj -c Release -o publish

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: sales-develop
          environment_name: Sales-develop-env
          version_label: ${{ github.sha }}
          deployment_package: publish
          region: us-east-1